name: chrono
channels:
  - projectchrono/label/release
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pychrono=8.0.0
  - irrlicht=1.8.5
  - numpy
  - matplotlib
  - json5
  - pytest
  - execnet=2.1.1
  - pytest-xdist=3.8.0
