name: chrono
channels:
  - projectchrono
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip
  - matplotlib
  - pandas
  - glfw[version='>=3.3,<4.0']
  - pychrono=8.0.0
  - pyqt
